# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    pageRef: /
    weight: 10
  - name: Papers
    pageRef: /publications
    weight: 11
  - name: Talks
    pageRef: /events
    weight: 12
  - name: News
    pageRef: /blog
    weight: 13
  - name: Experience
    pageRef: /experience
    weight: 20
  - name: Projects
    pageRef: /projects
    weight: 30
  - name: Courses
    pageRef: /courses
    weight: 40
